services:
  web:
    build: ./api
    image: openice-api
    env_file: .env
    command: python3.13 -m uvicorn app.main:app --workers 4 --host 0.0.0.0 --port 80
    restart: always
    volumes:
      - ./api:/usr/src/app
    ports:
      - "80:80"